In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib notebook


In [2]:
df=pd.read_csv('Car details v3.csv')

In [3]:
df

name  year  selling_price  km_driven    fuel  \
0           Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1     Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2         Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3        Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4           Maruti Swift VXI BSIII  2007         130000     120000  Petrol   
...                            ...   ...            ...        ...     ...   
8123             Hyundai i20 Magna  2013         320000     110000  Petrol   
8124         Hyundai Verna CRDi SX  2007         135000     119000  Diesel   
8125        Maruti Swift Dzire ZDi  2009         382000     120000  Diesel   
8126               Tata Indigo CR4  2013         290000      25000  Diesel   
8127               Tata Indigo CR4  2013         290000      25000  Diesel   

     seller_type transmission                 owner     mileage   engine  \
0     Individual       Manual           First Owner   23.4 kmpl  1248 CC   
1     Individual       Manual          Second Owner  21.14 kmpl  1498 CC   
2     Individual       Manual           Third Owner   17.7 kmpl  1497 CC   
3     Individual       Manual           First Owner   23.0 kmpl  1396 CC   
4     Individual       Manual           First Owner   16.1 kmpl  1298 CC   
...          ...          ...                   ...         ...      ...   
8123  Individual       Manual           First Owner   18.5 kmpl  1197 CC   
8124  Individual       Manual  Fourth & Above Owner   16.8 kmpl  1493 CC   
8125  Individual       Manual           First Owner   19.3 kmpl  1248 CC   
8126  Individual       Manual           First Owner  23.57 kmpl  1396 CC   
8127  Individual       Manual           First Owner  23.57 kmpl  1396 CC   

       max_power                     torque  seats  
0         74 bhp             190Nm@ 2000rpm    5.0  
1     103.52 bhp        250Nm@ 1500-2500rpm    5.0  
2         78 bhp      12.7@ 2,700(kgm@ rpm)    5.0  
3         90 bhp   22.4 kgm at 1750-2750rpm    5.0  
4       88.2 bhp      11.5@ 4,500(kgm@ rpm)    5.0  
...          ...                        ...    ...  
8123   82.85 bhp           113.7Nm@ 4000rpm    5.0  
8124     110 bhp  24@ 1,900-2,750(kgm@ rpm)    5.0  
8125    73.9 bhp             190Nm@ 2000rpm    5.0  
8126      70 bhp        140Nm@ 1800-3000rpm    5.0  
8127      70 bhp        140Nm@ 1800-3000rpm    5.0  

[8128 rows x 13 columns]

In [4]:
df.seats.unique()

array([ 5.,  4., nan,  7.,  8.,  6.,  9., 10., 14.,  2.])

In [5]:
X=df.drop(['name','torque','selling_price'],axis=1)
y=df['selling_price']

In [6]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   year          8128 non-null   int64  
 1   km_driven     8128 non-null   int64  
 2   fuel          8128 non-null   object 
 3   seller_type   8128 non-null   object 
 4   transmission  8128 non-null   object 
 5   owner         8128 non-null   object 
 6   mileage       7907 non-null   object 
 7   engine        7907 non-null   object 
 8   max_power     7913 non-null   object 
 9   seats         7907 non-null   float64
dtypes: float64(1), int64(2), object(7)
memory usage: 635.1+ KB


In [7]:
df.isnull().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           222
seats            221
dtype: int64

In [8]:
X['mileage']=X['mileage'].str.replace(r'( .*)', '').astype('float64')

<ipython-input-8-ff80ae6f4687>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  X['mileage']=X['mileage'].str.replace(r'( .*)', '').astype('float64')


In [9]:
X['engine']=X['engine'].str.replace(r'( .*)', '').astype('float64')

<ipython-input-9-8f68afb5a6b9>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  X['engine']=X['engine'].str.replace(r'( .*)', '').astype('float64')


In [10]:
X['max_power']=X['max_power'].str.replace(r'( .*)', '')#.astype('float64')

<ipython-input-10-d2b1bcbc7b65>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  X['max_power']=X['max_power'].str.replace(r'( .*)', '')#.astype('float64')


In [11]:
X.max_power.unique()

array(['74', '103.52', '78', '90', '88.2', '81.86', '57.5', '37', '67.1',
       '68.1', '108.45', '60', '73.9', nan, '67', '82', '88.5', '46.3',
       '88.73', '64.1', '98.6', '88.8', '83.81', '83.1', '47.3', '73.8',
       '34.2', '35', '81.83', '40.3', '121.3', '138.03', '160.77',
       '117.3', '116.3', '83.14', '67.05', '168.5', '100', '120.7',
       '98.63', '175.56', '103.25', '171.5', '100.6', '174.33', '187.74',
       '170', '78.9', '88.76', '86.8', '108.495', '108.62', '93.7',
       '103.6', '98.59', '189', '67.04', '68.05', '58.2', '82.85',
       '81.80', '73', '120', '94.68', '160', '65', '155', '69.01',
       '126.32', '138.1', '83.8', '126.2', '98.96', '62.1', '86.7', '188',
       '214.56', '177', '280', '148.31', '254.79', '190', '177.46', '204',
       '141', '117.6', '241.4', '282', '150', '147.5', '108.5', '103.5',
       '183', '181.04', '157.7', '164.7', '91.1', '400', '68', '75',
       '85.8', '87.2', '53', '118', '103.2', '83', '84', '58.16',
       '147.

In [12]:
X = X.replace(r'^\s*$', np.nan, regex=True)

In [13]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   year          8128 non-null   int64  
 1   km_driven     8128 non-null   int64  
 2   fuel          8128 non-null   object 
 3   seller_type   8128 non-null   object 
 4   transmission  8128 non-null   object 
 5   owner         8128 non-null   object 
 6   mileage       7907 non-null   float64
 7   engine        7907 non-null   float64
 8   max_power     7912 non-null   object 
 9   seats         7907 non-null   float64
dtypes: float64(3), int64(2), object(5)
memory usage: 635.1+ KB


In [14]:
X['max_power']=X['max_power'].astype('float64')

In [15]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   year          8128 non-null   int64  
 1   km_driven     8128 non-null   int64  
 2   fuel          8128 non-null   object 
 3   seller_type   8128 non-null   object 
 4   transmission  8128 non-null   object 
 5   owner         8128 non-null   object 
 6   mileage       7907 non-null   float64
 7   engine        7907 non-null   float64
 8   max_power     7912 non-null   float64
 9   seats         7907 non-null   float64
dtypes: float64(4), int64(2), object(4)
memory usage: 635.1+ KB


In [16]:
X['year']=2021-X['year']

In [17]:
X

year  km_driven    fuel seller_type transmission                 owner  \
0        7     145500  Diesel  Individual       Manual           First Owner   
1        7     120000  Diesel  Individual       Manual          Second Owner   
2       15     140000  Petrol  Individual       Manual           Third Owner   
3       11     127000  Diesel  Individual       Manual           First Owner   
4       14     120000  Petrol  Individual       Manual           First Owner   
...    ...        ...     ...         ...          ...                   ...   
8123     8     110000  Petrol  Individual       Manual           First Owner   
8124    14     119000  Diesel  Individual       Manual  Fourth & Above Owner   
8125    12     120000  Diesel  Individual       Manual           First Owner   
8126     8      25000  Diesel  Individual       Manual           First Owner   
8127     8      25000  Diesel  Individual       Manual           First Owner   

      mileage  engine  max_power  seats  
0       23.40  1248.0      74.00    5.0  
1       21.14  1498.0     103.52    5.0  
2       17.70  1497.0      78.00    5.0  
3       23.00  1396.0      90.00    5.0  
4       16.10  1298.0      88.20    5.0  
...       ...     ...        ...    ...  
8123    18.50  1197.0      82.85    5.0  
8124    16.80  1493.0     110.00    5.0  
8125    19.30  1248.0      73.90    5.0  
8126    23.57  1396.0      70.00    5.0  
8127    23.57  1396.0      70.00    5.0  

[8128 rows x 10 columns]

In [18]:
print(X['fuel'].unique())
print(X['seller_type'].unique())
print(X['transmission'].unique())
print(X['owner'].unique())



['Diesel' 'Petrol' 'LPG' 'CNG']
['Individual' 'Dealer' 'Trustmark Dealer']
['Manual' 'Automatic']
['First Owner' 'Second Owner' 'Third Owner' 'Fourth & Above Owner'
 'Test Drive Car']


In [19]:
# Dummy Variable Traps
X=pd.get_dummies(X,drop_first=True)

In [20]:
X.head()

year  km_driven  mileage  engine  max_power  seats  fuel_Diesel  fuel_LPG  \
0     7     145500    23.40  1248.0      74.00    5.0            1         0   
1     7     120000    21.14  1498.0     103.52    5.0            1         0   
2    15     140000    17.70  1497.0      78.00    5.0            0         0   
3    11     127000    23.00  1396.0      90.00    5.0            1         0   
4    14     120000    16.10  1298.0      88.20    5.0            0         0   

   fuel_Petrol  seller_type_Individual  seller_type_Trustmark Dealer  \
0            0                       1                             0   
1            0                       1                             0   
2            1                       1                             0   
3            0                       1                             0   
4            1                       1                             0   

   transmission_Manual  owner_Fourth & Above Owner  owner_Second Owner  \
0                    1                           0                   0   
1                    1                           0                   1   
2                    1                           0                   0   
3                    1                           0                   0   
4                    1                           0                   0   

   owner_Test Drive Car  owner_Third Owner  
0                     0                  0  
1                     0                  0  
2                     0                  1  
3                     0                  0  
4                     0                  0

In [21]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   year                          8128 non-null   int64  
 1   km_driven                     8128 non-null   int64  
 2   mileage                       7907 non-null   float64
 3   engine                        7907 non-null   float64
 4   max_power                     7912 non-null   float64
 5   seats                         7907 non-null   float64
 6   fuel_Diesel                   8128 non-null   uint8  
 7   fuel_LPG                      8128 non-null   uint8  
 8   fuel_Petrol                   8128 non-null   uint8  
 9   seller_type_Individual        8128 non-null   uint8  
 10  seller_type_Trustmark Dealer  8128 non-null   uint8  
 11  transmission_Manual           8128 non-null   uint8  
 12  owner_Fourth & Above Owner    8128 non-null   uint8  
 13  own

In [22]:
X.isnull().sum()

year                              0
km_driven                         0
mileage                         221
engine                          221
max_power                       216
seats                           221
fuel_Diesel                       0
fuel_LPG                          0
fuel_Petrol                       0
seller_type_Individual            0
seller_type_Trustmark Dealer      0
transmission_Manual               0
owner_Fourth & Above Owner        0
owner_Second Owner                0
owner_Test Drive Car              0
owner_Third Owner                 0
dtype: int64

In [23]:
X['mileage'].fillna(X['mileage'].median(),inplace=True)
X['engine'].fillna(X['engine'].median(),inplace=True)
X['max_power'].fillna(X['max_power'].median(),inplace=True)
X['seats'].fillna(X['seats'].median(),inplace=True)

In [24]:
X.isnull().sum()

year                            0
km_driven                       0
mileage                         0
engine                          0
max_power                       0
seats                           0
fuel_Diesel                     0
fuel_LPG                        0
fuel_Petrol                     0
seller_type_Individual          0
seller_type_Trustmark Dealer    0
transmission_Manual             0
owner_Fourth & Above Owner      0
owner_Second Owner              0
owner_Test Drive Car            0
owner_Third Owner               0
dtype: int64

In [25]:
X.seats.unique()

array([ 5.,  4.,  7.,  8.,  6.,  9., 10., 14.,  2.])

In [26]:
X=X.astype('float64')

In [27]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   year                          8128 non-null   float64
 1   km_driven                     8128 non-null   float64
 2   mileage                       8128 non-null   float64
 3   engine                        8128 non-null   float64
 4   max_power                     8128 non-null   float64
 5   seats                         8128 non-null   float64
 6   fuel_Diesel                   8128 non-null   float64
 7   fuel_LPG                      8128 non-null   float64
 8   fuel_Petrol                   8128 non-null   float64
 9   seller_type_Individual        8128 non-null   float64
 10  seller_type_Trustmark Dealer  8128 non-null   float64
 11  transmission_Manual           8128 non-null   float64
 12  owner_Fourth & Above Owner    8128 non-null   float64
 13  own

In [28]:
import seaborn as sns
plt.figure(figsize=(12,10))
sns.heatmap(X.corr(),annot=True)
plt.tight_layout()


<IPython.core.display.Javascript object>

In [29]:
# feature Imoprtance
from  sklearn.ensemble import ExtraTreesRegressor
model=ExtraTreesRegressor()
model.fit(X,y)

ExtraTreesRegressor()

In [30]:
model.feature_importances_

array([1.59166596e-01, 3.87669095e-02, 2.18838827e-02, 7.79883656e-02,
       3.03285443e-01, 1.12301527e-02, 3.20834453e-02, 5.96722667e-06,
       2.27542967e-02, 2.82856293e-02, 1.43234310e-03, 2.84866307e-01,
       2.59761796e-04, 1.20450649e-02, 5.07155177e-03, 8.74283564e-04])

In [31]:
plt.style.use('seaborn')
plt.barh(X.columns,model.feature_importances_)
plt.tight_layout()

In [32]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.2,random_state=1)

In [33]:
X_train.shape,X_test.shape

((6502, 16), (1626, 16))

In [34]:
from sklearn.linear_model import LinearRegression
mod=LinearRegression()
mod.fit(X_train,y_train)
mod.score(X_test,y_test)

0.6405902897673963

In [35]:
from sklearn.ensemble import RandomForestRegressor
r=RandomForestRegressor(random_state=0)
r.fit(X_train,y_train)
predictions=r.predict(X_test)
r.score(X_test,y_test)

0.9711961688968753

In [36]:
# import pickle
# # open a file, where you ant to store the data
# file = open('model.pkl', 'wb')

# # dump information to that file
# pickle.dump(r, file)


In [49]:
r.predict([[5, 100000, 20.0, 1500, 90, 5, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0]])

array([600459.99])

In [38]:
# import pickle
# model = pickle.load(open('model.pkl', 'rb'))

In [65]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,rf_random.predict(X_test))

83713.38352305412